// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCYPRQdD__FzHFMpunT6MnSWeiNstkcrhc',
//     appId: '1:84122034310:android:4cba892d9d9fd6317cf107',
//     messagingSenderId: '84122034310',
//     projectId: 'actives-14f7b',
//     databaseURL: 'https://actives-14f7b-default-rtdb.firebaseio.com',
//     storageBucket: 'actives-14f7b.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBSsPd9YrOwlolkZa_VEAVaKgqEZYG2KfA',
//     appId: '1:84122034310:ios:cc15978fea2080cd7cf107',
//     messagingSenderId: '84122034310',
//     projectId: 'actives-14f7b',
//     databaseURL: 'https://actives-14f7b-default-rtdb.firebaseio.com',
//     storageBucket: 'actives-14f7b.appspot.com',
//     androidClientId: '84122034310-63sicailje5a0ku99fht6mbq71u5qfa1.apps.googleusercontent.com',
//     iosClientId: '84122034310-p294638tl52n1lht132git36v988q0f4.apps.googleusercontent.com',
//     iosBundleId: 'com.example.activesVendors',
//   );
// }
